### ISSUE TITLE
Module crashing HH

### ISSUE THREAD

**Issue by xaro1** [GreenMeteor/humhub-geolocation-module#2]
Module unusable as is. HH is crashing because of bad module namespace (what is "conerd" ?) and  Undefined index: sortOrder.

**Comment by Felli** [comment]
Should be fixed, please test again.

**Comment by xaro1** [comment]
Nope. Still crashing. Another namespace problem in assets and Undefined index: sortOrder.

**Comment by Felli** [comment]
I'll look into the `sortOrder` issue in a second.

**Comment by Felli** [comment]
Could you try installing once more from the latest push to the repo?

**Comment by xaro1** [comment]
HH don't crash anymore when user profile is in english but module don't do anything. With another language, top navigation bar is broken.

**Comment by Felli** [comment]
Could you provide an error stack?

**Comment by xaro1** [comment]
I don't get any error in logs anymore, just top bar broken like an "empty" button between Spaces and Dashboard pointing to geolocation/index. When click on it, I'm redirected to Directory.

**Comment by Felli** [comment]
Seems to be working for me now, are you using any other modules that affect the directory page(s) such as the enterprise module or others?

**Comment by xaro1** [comment]
Yes, Bookmarks module and link button from custom pages.

**Comment by Felli** [comment]
This module itself overwrites the whole directory core module so any tabs that you create with Custom Pages module that goes into the directory will not show because you're no longer using the core directory but this module's overwritten version, as for the Bookmarks module, I'm not sure why this module wouldn't work with this one @staxDB does amazing work so I don't think it's any compatibility issues between these two modules. :thinking:

**Comment by xaro1** [comment]
This issue appear only when using another language than English.

**Comment by xaro1** [comment]
Maybe around this `if ($item['label'] == Yii::t('GeolocationModule.base', 'Directory')){` ?

**Comment by Felli** [comment]
Once I'm back at my computer I'll look into this issue.

**Comment by Felli** [comment]
Done a few updates, I'm not sure why the code snippet isn't working for you, but I've removed it from our personal translations and reverted it to HumHub's core translations so it should work as far as enabling it as well as viewing the directory tab, please provide more information if any other issues happen.

**Comment by xaro1** [comment]
Tested today and all seems working normally 👍 

I was wrong about what this module was supposed to do. Thanks anyway for quick bug resolving.
